export const PLANNING_COPY = {
  activities: {
    pageTitle: "Activiteiten",
    pageDescription: "Beheer het activiteitencatalogus voor planning.",
    newTitle: "Activiteit toevoegen",
    editTitle: "Activiteit bewerken",
    emptyTitle: "Nog geen activiteiten",
    emptyDescription:
      "Maak een activiteitencatalogus aan met titel, beschrijving en vereisten.",
    addButton: "Activiteit toevoegen",
    saveButton: "Opslaan",
    cancelButton: "Annuleren",
    deactivateButton: "Deactiveren",
    reactivateButton: "Heractiveren",
    activeBadge: "Actief",
    inactiveBadge: "Inactief",
    listError: "Activiteiten laden mislukt.",
    fields: {
      title: "Titel",
      description: "Beschrijving",
      descriptionHint:
        "Beschrijf wat de activiteit inhoudt. Deze tekst helpt bij toekomstige planning.",
      category: "Categorie",
      intensity: "Intensiteit",
      location: "Standaardlocatie",
      allowedSettings: "Mogelijke settings",
      allowedSettingsHint: "Waar kan deze activiteit plaatsvinden?",
      defaultDuration: "Standaardduur (minuten)",
      minParticipants: "Min. deelnemers",
      maxParticipants: "Max. deelnemers",
      requiresSupervision: "Begeleiding vereist",
      requiresVolunteer: "Vrijwilliger gewenst",
      mobilityNotes: "Mobiliteit / ondersteuning (optioneel)",
    },
  },
  categoryLabels: {
    creative: "Creatief",
    movement: "Beweging",
    social: "Sociaal",
    relaxation: "Ontspanning",
    other: "Overig",
  },
  intensityLabels: {
    low: "Laag",
    medium: "Gemiddeld",
    high: "Hoog",
  },
  allowedSettingLabels: {
    bed: "Bed",
    chair: "Stoel",
    room: "Kamer",
    ward: "Afdeling",
    outside: "Buiten",
  },
  recurring: {
    pageTitle: "Terugkerende planning",
    pageDescription: "Wekelijkse activiteitenschema's die automatisch sessies aanmaken.",
    newTitle: "Terugkerend schema toevoegen",
    editTitle: "Terugkerend schema bewerken",
    emptyTitle: "Nog geen terugkerende schema's",
    emptyDescription:
      "Plan bijvoorbeeld elke dinsdag schilderen van 10:00 tot 11:30.",
    addButton: "Schema toevoegen",
    saveButton: "Opslaan",
    badge: "Terugkerend",
    fields: {
      activity: "Activiteit",
      dayOfWeek: "Weekdag",
      startTime: "Starttijd",
      endTime: "Eindtijd",
      location: "Locatie (optioneel)",
      locationHint: "Overschrijft de standaardlocatie van de activiteit.",
      minParticipants: "Min. deelnemers (optioneel)",
      maxParticipants: "Max. deelnemers (optioneel)",
    },
  },
  sessions: {
    pageTitle: "Sessies",
    pageDescription: "Plan eenmalige sessies en beheer deelnemers en vrijwilligers.",
    newTitle: "Eenmalige sessie plannen",
    detailTitle: "Sessiedetails",
    emptyTitle: "Nog geen sessies",
    emptyDescription: "Maak een eenmalige sessie aan of genereer sessies via terugkerende schema's.",
    addOneOffButton: "Eenmalige sessie",
    saveButton: "Sessie aanmaken",
    listError: "Sessies laden mislukt.",
    participantsTitle: "Patiënten",
    participantsHint: "Selecteer opgenomen patiënten voor deze sessie.",
    volunteersTitle: "Vrijwilligers",
    volunteersHint: "Wijs vrijwilligers handmatig toe.",
    saveAssignmentsButton: "Toewijzingen opslaan",
    unsavedAssignmentsHint:
      "Sla eerst de toewijzingen op voordat je de status wijzigt.",
    patientsLoadError: "Patiënten konden niet worden geladen.",
    volunteersLoadError: "Vrijwilligers konden niet worden geladen.",
    emptyPatients: "Geen actieve opnames gevonden.",
    emptyVolunteers: "Geen vrijwilligers gevonden.",
    statusActions: {
      propose: "Voorstellen",
      confirm: "Bevestigen",
      backToDraft: "Terug naar concept",
      complete: "Voltooien",
      cancel: "Annuleren",
    },
    fields: {
      activity: "Activiteit",
      sessionDate: "Datum",
      startTime: "Starttijd",
      endTime: "Eindtijd",
      location: "Locatie",
      minParticipants: "Min. deelnemers",
      maxParticipants: "Max. deelnemers",
      notes: "Notities (optioneel)",
    },
    filters: {
      status: "Status",
      kind: "Type",
      all: "Alle",
    },
  },
  overview: {
    pageTitle: "Activiteitenplanning",
    pageDescription: "Overzicht per locatie voor vandaag.",
    addSessionButton: "Sessie plannen",
    emptyTitle: "Geen sessies vandaag",
    emptyDescription: "Plan een sessie of activeer terugkerende schema's.",
    listError: "Planning kon niet worden geladen.",
    volunteersTodayTitle: "Vrijwilligers vandaag",
    volunteersTodayEmpty: "Geen beschikbare vrijwilligers vandaag.",
    volunteersTodayError: "Beschikbaarheid kon niet worden geladen.",
  },
  calendar: {
    pageTitle: "Kalender",
    pageDescription: "Weekoverzicht van geplande sessies.",
    listError: "Kalender kon niet worden geladen.",
    emptyDay: "Geen sessies",
  },
  coordinatorVolunteers: {
    pageTitle: "Vrijwilligers",
    pageDescription: "Bekijk vrijwilligers en hun beschikbaarheid.",
    emptyTitle: "Geen vrijwilligers",
    emptyDescription: "Maak vrijwilligersaccounts aan via beheer.",
    listError: "Vrijwilligers konden niet worden geladen.",
    recurringTitle: "Wekelijkse beschikbaarheid",
    exceptionsTitle: "Uitzonderingen",
    noRecurring: "Geen vaste tijdvakken",
    noExceptions: "Geen uitzonderingen",
    bioTitle: "Over mij",
  },
} as const;
