export const PLANNING_COPY = {
  activities: {
    pageTitle: "Activiteiten",
    pageDescription: "Beheer het activiteitencatalogus voor planning.",
    newTitle: "Activiteit toevoegen",
    editTitle: "Activiteit bewerken",
    emptyTitle: "Nog geen activiteiten",
    emptyDescription:
      "Maak een activiteitencatalogus aan met titel, beschrijving en vereisten.",
    addButton: "Activiteit toevoegen",
    saveButton: "Opslaan",
    cancelButton: "Annuleren",
    deactivateButton: "Deactiveren",
    reactivateButton: "Heractiveren",
    activeBadge: "Actief",
    inactiveBadge: "Inactief",
    listError: "Activiteiten laden mislukt.",
    fields: {
      title: "Titel",
      description: "Beschrijving",
      descriptionHint:
        "Beschrijf wat de activiteit inhoudt. Deze tekst helpt bij toekomstige planning.",
      category: "Categorie",
      intensity: "Intensiteit",
      location: "Standaardlocatie",
      allowedSettings: "Mogelijke settings",
      allowedSettingsHint: "Waar kan deze activiteit plaatsvinden?",
      defaultDuration: "Standaardduur (minuten)",
      minParticipants: "Min. deelnemers",
      maxParticipants: "Max. deelnemers",
      mobilityNotes: "Mobiliteit / ondersteuning (optioneel)",
    },
  },
  categoryLabels: {
    creative: "Creatief",
    movement: "Beweging",
    social: "Sociaal",
    relaxation: "Ontspanning",
    other: "Overig",
  },
  intensityLabels: {
    low: "Laag",
    medium: "Gemiddeld",
    high: "Hoog",
  },
  allowedSettingLabels: {
    bed: "Bed",
    chair: "Stoel",
    room: "Kamer",
    ward: "Afdeling",
    outside: "Buiten",
  },
  recurring: {
    pageTitle: "Terugkerende planning",
    pageDescription: "Wekelijkse activiteitenschema's die automatisch sessies aanmaken.",
    newTitle: "Terugkerend schema toevoegen",
    editTitle: "Terugkerend schema bewerken",
    emptyTitle: "Nog geen terugkerende schema's",
    emptyDescription:
      "Plan bijvoorbeeld elke dinsdag schilderen van 10:00 tot 11:30.",
    addButton: "Schema toevoegen",
    saveButton: "Opslaan",
    badge: "Terugkerend",
    fields: {
      activity: "Activiteit",
      dayOfWeek: "Weekdag",
      startTime: "Starttijd",
      endTime: "Eindtijd",
      location: "Locatie (optioneel)",
      locationHint: "Overschrijft de standaardlocatie van de activiteit.",
      minParticipants: "Min. deelnemers (optioneel)",
      maxParticipants: "Max. deelnemers (optioneel)",
    },
  },
  sessions: {
    pageTitle: "Sessies",
    pageDescription: "Plan eenmalige sessies en beheer deelnemers en vrijwilligers.",
    newTitle: "Eenmalige sessie plannen",
    detailTitle: "Sessiedetails",
    emptyTitle: "Nog geen sessies",
    emptyDescription: "Maak een eenmalige sessie aan of genereer sessies via terugkerende schema's.",
    addOneOffButton: "Eenmalige sessie",
    saveButton: "Sessie aanmaken",
    listError: "Sessies laden mislukt.",
    participantsTitle: "Patiënten",
    participantsHint: "Selecteer opgenomen patiënten voor deze sessie.",
    facilitatorsTitle: "Begeleiders (optioneel)",
    facilitatorsHint: "Wijs bestaande accounts toe die de activiteit begeleiden.",
    facilitatorsSearchPlaceholder: "Zoek op naam…",
    saveAssignmentsButton: "Toewijzingen opslaan",
    unsavedAssignmentsHint:
      "Sla eerst de toewijzingen op voordat je publiceert.",
    patientsLoadError: "Patiënten konden niet worden geladen.",
    facilitatorsLoadError: "Begeleiders konden niet worden geladen.",
    emptyPatients: "Geen actieve opnames gevonden.",
    emptyFacilitators: "Geen geschikte accounts gevonden.",
    belowMinParticipantsWarning:
      "Minder dan {min} deelnemers geselecteerd. Dit is een voorkeursminimum, geen blokkade.",
    editScheduleTitle: "Planning bewerken",
    saveScheduleButton: "Planning opslaan",
    statusActions: {
      publish: "Publiceren",
      complete: "Voltooien",
      cancel: "Annuleren",
    },
    fields: {
      activity: "Activiteit",
      sessionDate: "Datum",
      startTime: "Starttijd",
      endTime: "Eindtijd",
      location: "Locatie",
      minParticipants: "Min. deelnemers",
      maxParticipants: "Max. deelnemers",
      notes: "Notities (optioneel)",
    },
    schedule: {
      endTimeHint: "Berekend op basis van de actieve duur.",
      defaultDurationHint: "Standaardduur van de activiteit: {minutes} minuten.",
      missingDefaultDurationHint:
        "Deze activiteit heeft geen standaardduur. Geef een duur op voor deze planning.",
      useCustomDuration: "Aangepaste duur gebruiken",
      customDurationMinutes: "Duur (minuten)",
    },
    filters: {
      status: "Status",
      kind: "Type",
      all: "Alle",
    },
  },
  overview: {
    pageTitle: "Activiteitenplanning",
    pageDescription: "Overzicht per locatie voor vandaag.",
    addSessionButton: "Activiteit plannen",
    emptyTitle: "Geen sessies vandaag",
    emptyDescription: "Plan een sessie of activeer terugkerende schema's.",
    listError: "Planning kon niet worden geladen.",
    volunteersTodayTitle: "Vrijwilligers vandaag",
    volunteersTodayEmpty: "Geen beschikbare vrijwilligers vandaag.",
    volunteersTodayError: "Beschikbaarheid kon niet worden geladen.",
  },
  series: {
    pageTitle: "Reeksen",
    pageDescription: "Beheer terugkerende activiteitenreeksen en gekoppelde sessies.",
    badge: "Reeks",
    loading: "Reeksen laden…",
    listError: "Reeksen laden mislukt.",
    emptyTitle: "Nog geen reeksen",
    emptyDescription: "Plan een terugkerende activiteit via Activiteit plannen.",
    detailButton: "Reeks bekijken",
    detailTitle: "Reeksdetails",
    backButton: "Terug naar reeksen",
    notFound: "Reeks niet gevonden.",
    overviewTitle: "Reeksgegevens",
    seriesPeriodLabel: "Periode",
    sessionsTitle: "Gekoppelde sessies",
    emptySessions: "Nog geen sessies gegenereerd.",
    detachedLabel: "aangepast",
    openSessionButton: "Sessie openen",
    reminderTitle: "Reeksherinnering",
    endingSoonMessage:
      "Deze reeks loopt binnen 14 dagen af. Verleng de reeks of laat hem aflopen.",
    endedMessage: "Deze reeks is beëindigd.",
    extendButton: "Reeks verlengen",
    letEndButton: "Laat reeks aflopen",
    endingSoonBadge: "Loopt binnenkort af",
    endedBadge: "Beëindigd",
    structuralEditHint: "Structurele wijzigingen (weekdag of tijd) via",
    structuralEditLink: "reeks bewerken",
    actionError: "Actie mislukt. Probeer het opnieuw.",
  },
  calendar: {
    pageTitle: "Kalender",
    pageDescription: "Weekoverzicht van geplande sessies.",
    listError: "Kalender kon niet worden geladen.",
    emptyDay: "Geen sessies",
  },
  coordinatorVolunteers: {
    pageTitle: "Vrijwilligers",
    pageDescription: "Bekijk vrijwilligers en hun beschikbaarheid.",
    emptyTitle: "Geen vrijwilligers",
    emptyDescription: "Maak vrijwilligersaccounts aan via beheer.",
    listError: "Vrijwilligers konden niet worden geladen.",
    recurringTitle: "Wekelijkse beschikbaarheid",
    exceptionsTitle: "Uitzonderingen",
    noRecurring: "Geen vaste tijdvakken",
    noExceptions: "Geen uitzonderingen",
    bioTitle: "Over mij",
  },
  plan: {
    pageTitle: "Activiteit plannen",
    pageDescription:
      "Plan een eenmalige sessie of een terugkerende reeks in een paar stappen.",
    steps: {
      activity: "Activiteit",
      kind: "Type",
      schedule: "Planning",
      facilitators: "Begeleiders",
    },
    kindLabels: {
      one_off: "Eenmalig",
      recurring: "Terugkerend",
    },
    kindDescriptions: {
      one_off: "Plan één sessie op een specifieke datum.",
      recurring: "Maak een reeks die automatisch sessies genereert.",
    },
    chooseActivityPlaceholder: "Kies een activiteit",
    newActivityHint: "Staat de activiteit nog niet in het catalogus?",
    newActivityLink: "Nieuwe activiteit aanmaken",
    selectedActivityLabel: "Gekozen activiteit",
    summaryPrefix: "Je plant",
    nextButton: "Volgende",
    backButton: "Vorige",
    saveButton: "Opslaan",
    cancelButton: "Annuleren",
    saveError: "Opslaan mislukt. Probeer het opnieuw.",
  },
} as const;
